apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-k8s-service-one
spec:
  selector:
    matchLabels:
      app: service-one
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: service-one
    spec:
      containers:
        - name: spring-cloud-k8s-service-one
          image: lhwarthas/spring-cloud-k8s-service-one:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10010
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-address
                  key: eureka_service_address
            - name: SERVER_PORT
              value: '10010'
          livenessProbe:
            httpGet:
              path: /
              port: 10010
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 10010
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "curl -X POST http://localhost:$SERVER_PORT/service-actuator/serviceregistry?status=DOWN -H 'Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8' && sleep 15"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 60