spring:
  profiles:
    active: prd
  application:
    name: cloud-eureka-server

server:
  port: 8761

eureka:
  server:
    # Eureka Server readOnlyCacheMap更新周期
    response-cache-update-interval-ms: 5000